openapi: 3.0.3
info:
  title: Greetings API
  version: 1.0.0
  description: This is a greetings API demonstrating a simple endpoint with query.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.yourdomain.com/v1
    description: Production server (v1)
  - url: https://staging-api.yourdomain.com/v1
    description: Staging server (v1)

security: 
  - api_key: []

paths:
  /hello:
    get:
      summary: Returns a greeting message
      description: This endpoint returns a greeting message. You can optionally provide a name to personalize the greeting.
      operationId: getGreeting
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: Ezinne
          required: false
          description: Name of the person to greet.
        - in: query
          name: lang
          schema:
            type: string
            enum: [en, es, fr, de]
            example: en
          required: false
          description: Language of the greeting (default is English)
      responses:
        '200':
          description: A successful response containing the greeting message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, John!
              examples:
                english:
                  value: { message: "Hello, Ezinne!" }
                french:
                  value: { message: "Bonjour, Ezinne!" }
                spanish:
                  value: { message: "¡Hola, Ezinne!" }
                igbo:
                  value: { message: "Ndeewo, Ezinne!" }
        '400':
          description: Bad Request - Invalid input.
        '500':
          description: Internal Server Error - An error occurred on the server.
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
